version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: /.github/ci/python
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /.github/ci/node
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
